import type { Metadata } from "next";

import ThemeRegistry from "@/styles/theme/ThemeRegistry";
import ReduxProvider from "@/store/provider";
import MainLayout from "@/layouts/MainLayout";

export const metadata: Metadata = {
  title: "Market place",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <ThemeRegistry>
            <MainLayout>{children}</MainLayout>
          </ThemeRegistry>
        </ReduxProvider>
      </body>
    </html>
  );
}
